---
- name: Pull docker image from dockerHub
  hosts: ubuntu18
  remote_user : udith
  tasks:
    - name: Pull calculator image
      docker_image:
        name: udithm/devops-calc
        source: pull